### ISSUE TITLE
Catalog on movie simkl android tv stremio blank, & some movie error getting meta

### ISSUE THREAD

**Issue by ericvlog** [aliyss/syncribullet#4]
hello, thanks for wonderful addons.

It has some bug on **android tv stremio**, the main page movie catalog won't load poster.it just show blank.

On android version, some movies on the catalog say providing this item have been removed.
example movie.

suitable flesh
desperation road

Thanks for your wonderful addons, appreciate.

**Comment by aliyss** [comment]
I think the android TV stuff should be fixed...

The suitable flesh stuff is weird as it seems Simkl has the IMDb id, but stremio also has it. But the one I am passing does not get recognised.

**Comment by ericvlog** [comment]
> I think the android TV stuff should be fixed...
> 
> The suitable flesh stuff is weird as it seems Simkl has the IMDb id, but stremio also has it. But the one I am passing does not get recognised.

I have test other add-ons call simkl watchlist, that can get meta & information on android TV stremio without problem, but it only watchlist mo sync.

**Comment by gecXMAN** [comment]
Same here, on android mobile and on windows is working fine. 
TV lists are working fine everywhere, aren't they also using imdb ID?
Unfortunately because of this these great addon is unusable on android tv.

**Comment by aliyss** [comment]
Right so let me quickly explain what is going on.

As far as I understand it, I can pass the imdb id on stremio and it will go and fill the metadata itself by using cinemeta. For some reason this does not work on android TV.

The other watchlist addon prefetches the metadata by using the tvdb api and then sends it to stremio.

I am currently working on the tvdb stuff... to get the data beforehand as well, due to this exact issue. However here I am hoping for stremio to actually have it fill.

Can you guys provide some answers to these questions:
- Are the posters loading?
- When clicking into the movie do you get the details?
- Is it for more or less all movies?

**Comment by aliyss** [comment]
Heya @ericvlog @gecXMAN 

I tried fixing some stuff for movies. Would it be possible to test it again.
It may need a general restart of stremio or try scrolling down even if it seems empty.

Many thanks in advance

**Comment by gecXMAN** [comment]
- Are the posters loading?
   - YES
   - When clicking into the movie do you get the details?
   - NO
   - Is it for more or less all movies?
   - FOR ALL

**Comment by gecXMAN** [comment]
It's working now :)
Thank You !

**Comment by ericvlog** [comment]
all poster at android tv stremio show up ~~!! thanks !!
